name: DemoGen

options:
  bundleIdPrefix: com.DemoGen
  deploymentTarget: '12.0'

targets:
  DemoGen:
    type: application
    platform: iOS
    deploymentTarget: 14.1
    bundleIdPrefix: com.DemoGen
    sources:
      - path: "DemoGen"
    dependencies:
      - target: MoreScreen
    settings:
      base:
        DISPLAY_NAME: "Wake on LAN"
        INFOPLIST_FILE: "DemoGen/Info.plist"

  MainScreen:
    templates:
      - Framework
    templateAttributes:
      frameworkName: MainScreen
    deploymentTarget: 14.1
    sources:
      - path: "DemoGen/Modules/${frameworkName}"

  MoreScreen:
    templates:
      - Framework
    templateAttributes:
      frameworkName: MoreScreen
    deploymentTarget: 14.1
    sources:
      - path: "DemoGen/Modules/${frameworkName}"

  SerialsScreen:
    templates:
      - Framework
    templateAttributes:
      frameworkName: SerialsScreen
    deploymentTarget: 14.1
    sources:
      - path: "DemoGen/Modules/${frameworkName}"

targetTemplates:
  Framework:
    settings:
      base:
        INFOPLIST_FILE: "DemoGen/Modules/${frameworkName}/Info.plist"
    platform: iOS
    type: framework
